server:
  port: 8000
  servlet:
    context-path: /api
spring:
  application:
    name: chat
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${qyp.db.host}:3306/chat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${qyp.db.username}
    password: ${qyp.db.password}
  redis:
    host: ${qyp.redis.host}
    port: 6379
    password: ${qyp.redis.password}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler

logging:
  level:
    com.qyp.chat: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

knife4j:
  enable: true
  openapi:
    title: 聊天室——接口文档
    description: "聊天室接口文档"
    email: 2740123221@qq.com
    concat: qyp
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.qyp.chat.controller


project:
  folder: d:/web/chat/
admin:
  emails: 123@qq.com
ws:
  port: 5051